define(["module"],function(module){
	var baseUrl=module.uri.substring(0,module.uri.lastIndexOf('/'));
	var modPath="";
	requirejs.config({
		"waitSeconds":0,
		"baseUrl":baseUrl,
		"urlArgs":["cachebust",(new Date()).getTime()].join("="),
		"paths":{
			"ace":modPath+"vendor/ace/ace",
			"jquery":modPath+"vendor/jquery/jquery.3.5.1",
			"jquery-private":modPath+"vendor/jquery/jquery-private",
			"jspanel":modPath+"vendor/jspanel/jspanel",
			"jspanel.dock":modPath+"vendor/jspanel/jspanel.dock",
			"jspanel.contextmenu":modPath+"vendor/jspanel/jspanel.contextmenu",
			"css":modPath+"vendor/requirecss/css.min",
			"underscore":modPath+"vendor/underscore/underscore-min",
			"lodash":modPath+"vendor/lodash/lodash.min",
			"jquery.jsonForm":modPath+"vendor/jsonform/jsonform",
			"jsv":modPath+"vendor/jsv/jsv",
			"dx":modPath+"vendor/dx/20.2.5/dx.all",
			"kwe.filemanager":modPath+"vendor/kwe/filemanager/index.browser",
			"kwe.workbench":modPath+"vendor/kwe/workbench/index",
			"idutils":modPath+"vendor/kwe/idutils/index",
		},
		"config":{},
		"map":{
			"*":{},
			"jquery-private":{"jquery":"jquery"},
		},
		"shim":{
			"ace":{
				"deps":[],
				"exports":"ace"
			},
			"jspanel":{
				"deps":[],
				"exports":"jsPanel"
			},
			"jspanel.dock":{
				"deps":["jspanel"]
			},
			"underscore":{
				"deps":[],
				"exports":"_"
			},
			"lodash":{
				"deps":[],
				"exports":"_"
			},
			"jquery.jsonForm":{
				"deps":["jquery","underscore","jsv","ace","bootstrap","spectrum"],
			},
			"jsv":{
				"deps":[],
				"exports":"JSV"
			},
			"dx":{
				"deps":["jquery"],
				"exports":"jQuery.dxFileManager"
			},
		},
		"deps":[]
	});
});


