define(["module"],function(module){
	var baseUrl=module.uri.substring(0,module.uri.lastIndexOf('/'));
	var modPath="";
	var GOJA=true;
	requirejs.config({
		//"useParseEval":true,
		//"protocol":"ws://",
		"waitSeconds":0,
		"baseUrl":baseUrl,
		"paths":{
			"jquery":modPath+"vendor/jquery/jquery.3.5.1",
			"jquery-private":modPath+"vendor/jquery/jquery-private",
			"window":modPath+"vendor/kwe/window",
			"document":modPath+"vendor/kwe/document",
			"domino":modPath+"vendor/domino/domino",
			"lzstring":modPath+"vendor/lz-string/1.4.4/lz-string",
			"base64string":modPath+"vendor/lz-string/1.4.4/base64-string",
			"text":modPath+"vendor/requirejs/require.text",
			"sprintf":modPath+"vendor/sprintf/1.1.2/sprintf.min",
			"console":modPath+"vendor/kwe/console/index",
			"request":modPath+"vendor/kwe/request/index",
			"idutils":modPath+"vendor/kwe/idutils/index",
			"pathutils":modPath+"vendor/kwe/pathutils/index",
			"class":modPath+"vendor/kwe/class/class.goja",
			"kwe.cmdprocessor":modPath+"vendor/kwe/cmdprocessor/index",
			"kwe.terminal":modPath+"vendor/kwe/terminal/index.svc",
			"kwe.str2arg":modPath+"vendor/kwe/str2arg/index",
			"kwe.filemanager":modPath+"vendor/kwe/filemanager/index",
			"kwe.stringutils.pad":modPath+"vendor/kwe/stringutils/pad",
			"kwe.stringutils.arggen":modPath+"vendor/kwe/stringutils/arggen",
			"kwe.stringutils.getopt":modPath+"vendor/kwe/stringutils/getopt",
			"node-getopt":modPath+"vendor/node-getopt/getopt",
			"jshint":modPath+"vendor/jshint/2.6.3/jshint",
			"lodash":modPath+"vendor/lodash/lodash.min",
			"esprima":modPath+"vendor/esprima/2.7.3/esprima",
			"cyclejs":modPath+"vendor/cyclejs/cycle",
		},
		"packages":[],
		"config":{
			"text":{
				"env":"goja"
			}
		},
		"map":{
			"*":{},
		},
		"shim":{
			"sprintf":{
				"deps":[],
				"exports":"sprintf"
			},
			"jshint":{
				"deps":["lodash"],
				"exports":"JSHINT"
			},
			"lodash":{
				"deps":[],
				"exports":"_"
			},
			"esprima":{
				"deps":[],
				//"exports":"esutils"
			},

			"lzstring":{
				"deps":[],
				"exports":"LZString"
			},
			"base64string":{
				"deps":[],
				//"exports":""
			},
			"window":{
				"deps":[],
				"exports":"window"
			},
			"document":{
				"deps":["window"],
				"exports":"document"
			},


		},
		"deps":[]
	});
});
