define(["module"],function(module){
	var baseUrl=module.uri.substring(0,module.uri.lastIndexOf('/'));
	var modPath="";
	requirejs.config({
		"waitSeconds":0,
		"baseUrl":baseUrl,
		"urlArgs":["cachebust",(new Date()).getTime()].join("="),
		"paths":{
			"axios":modPath+"vendor/axios/0.21.0/axios",
			"ace":modPath+"vendor/ace/ace",
			"jquery":modPath+"vendor/jquery/jquery.3.5.1",
			"jquery-private":modPath+"vendor/jquery/jquery-private",
			"jspanel":modPath+"vendor/jspanel/jspanel",
			"jspanel.dock":modPath+"vendor/jspanel/jspanel.dock",
			"jspanel.contextmenu":modPath+"vendor/jspanel/jspanel.contextmenu",
			"css":modPath+"vendor/requirecss/css.min",
			"underscore":modPath+"vendor/underscore/underscore-min",
			"lodash":modPath+"vendor/lodash/lodash.min",
			"jquery.jsonForm":modPath+"vendor/jsonform/jsonform",
			"jsv":modPath+"vendor/jsv/jsv",
			"dx":modPath+"vendor/dx/20.2.5/dx.all",
			"jquery.terminal":modPath+"vendor/jqueryterminal/jquery.terminal-2.19.2",
			"wcwidth":modPath+"vendor/jqueryterminal/wcwidth",
			"ascii_table":modPath+"vendor/jqueryterminal/ascii_table",
			"autocomplete_menu":modPath+"vendor/jqueryterminal/autocomplete_menu",
			"unix_formatting":modPath+"vendor/jqueryterminal/unix_formatting",
			"xml_formatting":modPath+"vendor/jqueryterminal/xml_formatting",
			"kwe.filemanager":modPath+"vendor/kwe/filemanager/index.browser",
			"kwe.str2arg":modPath+"vendor/kwe/str2arg/index",
			"kwe.workbench":modPath+"vendor/kwe/workbench/index",
			"kwe.workbench.editor":modPath+"vendor/kwe/workbench/widgets/edit",
			"kwe.workbench.createfile":modPath+"vendor/kwe/workbench/widgets/createfile",
			"kwe.workbench.browser":modPath+"vendor/kwe/workbench/widgets/browser",
			"kwe.workbench.terminal":modPath+"vendor/kwe/workbench/widgets/terminal",
			"idutils":modPath+"vendor/kwe/idutils/index",
		},
		"config":{},
		"map":{
			"*":{},
			"jquery-private":{"jquery":"jquery"},
		},
		"shim":{
			"axios":{
				"deps":[],
				"exports":"axios"
			},
			"jquery.terminal":{
				"deps":["jquery","ascii_table",]
			},
			"wcwidth":{
				"deps":[]
			},
			"ascii_table":{
				"deps":["wcwidth"]
			},


			"ace":{
				"deps":[],
				"exports":"ace"
			},
			"jspanel":{
				"deps":[],
				"exports":"jsPanel"
			},
			"jspanel.dock":{
				"deps":["jspanel"]
			},
			"underscore":{
				"deps":[],
				"exports":"_"
			},
			"lodash":{
				"deps":[],
				"exports":"_"
			},
			"jquery.jsonForm":{
				"deps":["jquery","underscore","jsv","ace","bootstrap","spectrum"],
			},
			"jsv":{
				"deps":[],
				"exports":"JSV"
			},
			"dx":{
				"deps":["jquery"],
				"exports":"jQuery.dxFileManager"
			},
		},
		"deps":[]
	});
});


